-
   hosts: all
   gather_facts: true
   tasks:
      -
         name: update packages
         apt:
            update_cache: 'yes'
      -
         name: install required packages
         apt:
            pkg:
               - apt-transport-https
               - curl
               - ca-certificates
               - gnupg-agent
               - software-properties-common
      -
         name: add docker gpg key
         shell: >-
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo
            apt-key add -
      -
         name: add docker repository
         apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
            state: present
      - 
        name: update cache
        apt:
          update_cache: 'yes'
      -
         name: install docker
         apt:
            pkg:
               - docker-ce
               - docker-ce-cli
               - containerd.io
